/*	
 * topdev GmbH, erstellt am 02.10.2009 08:45
 *
 * $Author: Maribel Zamorano $
 * $Date: 2009-10-02 08:45:22 $
 * $Rev: _ $
 * -------------------------------------------
 * $Workfile: (01) akkradm.Untergruppe.sql $
 *
 */

if exists ( select * from sysobjects where id = object_id('akkradm.IO_UNTERGRUPPE ') and OBJECTPROPERTY(id, 'IsTable') = 1)
begin
	GOTO createView;
--	drop table akkradm.IO_UNTERGRUPPE ;
end;

create table akkradm.IO_UNTERGRUPPE (
	UNGR_ID				UDT_ID IDENTITY NOT FOR REPLICATION,


	MAND_ID				UDT_MANDANT		NOT NULL,
	EIGE_ID				UDT_EIGENTUEMER	NOT NULL,

	VESG_ID				UDT_ID			NOT NULL,
--  UGAR_ID				UDT_ID			NOT NULL,


	 UNGR_THEMA					nvarchar(255)	 NULL,  
	 UNGR_DT_BEGINN				datetime	 NOT NULL,
	 UNGR_DT_ENDE				datetime	 NOT NULL,
	 UNGR_MAX_TEILNEHMER		UDT_ANZAHL_I NOT NULL,
	 UNGR_#DT_BEGINN_ZEIT		UDT_UHRZEIT		 NULL,
	 UNGR_#DT_ENDE_ZEIT			UDT_UHRZEIT		 NULL,
	 UNGR_KZ_GESPERRT			UDT_BOOLEAN  NOT NULL,
	 UNGR_KZ_ANMELDUNG_ZUL		UDT_BOOLEAN  NOT NULL,
	 UNGR_KZ_NICHT_UEBERBUCHBAR UDT_BOOLEAN  NOT NULL,
	 UNGR_ANMELDEBLOCK			smallint         NULL,
	 UNGR_KZ_AUTO_VERGABE		UDT_BOOLEAN_TRUE NOT NULL,
	 UNGR_TEILNEHMER_ANZAHL		UDT_ANZAHL_S NOT NULL,

	

	UNGR_USER			UDT_USER	NOT NULL,
	UNGR_PTS			UDT_PTS		NOT NULL,
	UNGR_#PTS			UDT_#PTS	NULL,	
	UNGR_ID_INT			UDT_ID_0	NOT NULL,
	UNGR_UQID			UDT_UQID	NOT NULL ROWGUIDCOL,
	UNGR_KZ_FREIGABE	UDT_BOOLEAN	NOT NULL,
	UNGR_KZ_REPLIKATION	UDT_BOOLEAN	NOT NULL,
	UNGR_KZ_GELOESCHT	UDT_BOOLEAN	NOT NULL,


	CONSTRAINT PK_UNGR PRIMARY KEY CLUSTERED( UNGR_ID )
);

CREATE UNIQUE INDEX UNGR_IX_01_U ON akkradm.IO_UNTERGRUPPE ( UNGR_UQID );
CREATE INDEX		UNGR_IX_02	 ON akkradm.IO_UNTERGRUPPE ( UNGR_KZ_GELOESCHT );

createView:

if not exists ( select * from sysobjects where id = object_id('akkradm.T_UNTERGRUPPE ') and OBJECTPROPERTY(id, 'IsView') = 1)
begin
	exec( N'create view akkradm.T_UNTERGRUPPE  as select * from INFORMATION_SCHEMA.TABLES;' );
end
GO

alter view akkradm.T_UNTERGRUPPE (
		UNGR_ID,


		VESG_ID,
		UGAR_ID,

		UNGR_THEMA,  
		UNGR_DT_BEGINN,
		UNGR_DT_ENDE,
		UNGR_MAX_TEILNEHMER,
		UNGR_#DT_BEGINN_ZEIT,
		UNGR_#DT_ENDE_ZEIT,
		UNGR_KZ_GESPERRT,
		UNGR_KZ_ANMELDUNG_ZUL,
		UNGR_KZ_NICHT_UEBERBUCHBAR,
		UNGR_ANMELDEBLOCK,
		UNGR_KZ_AUTO_VERGABE,
		UNGR_TEILNEHMER_ANZAHL,

		UNGR_USER,
		UNGR_PTS,
		UNGR_#PTS

) as
select	UNGR_ID,

		VESG_ID,
		UGAR_ID,

		UNGR_THEMA,  
		UNGR_DT_BEGINN,
		UNGR_DT_ENDE,
		UNGR_MAX_TEILNEHMER,
		UNGR_#DT_BEGINN_ZEIT,
		UNGR_#DT_ENDE_ZEIT,
		UNGR_KZ_GESPERRT,
		UNGR_KZ_ANMELDUNG_ZUL,
		UNGR_KZ_NICHT_UEBERBUCHBAR,
		UNGR_ANMELDEBLOCK,
		UNGR_KZ_AUTO_VERGABE,
		UNGR_TEILNEHMER_ANZAHL,

		UNGR_USER,
		UNGR_PTS,
		UNGR_#PTS

from	akkradm.IO_UNTERGRUPPE 
where	UNGR_KZ_GELOESCHT = 0;

GO
