/*	
 * topdev GmbH, erstellt am 28.09.2009 16:30
 *
 * $Author: Maribel Zamorano $
 * $Date: 2009-09-28 16:30:25 $
 * $Rev: _ $
 * -------------------------------------------
 * $Workfile: (01) akkradm.Veranstaltung.sql $
 *
 */

if exists ( select * from sysobjects where id = object_id('akkradm.IO_VERANSTALTUNG') and OBJECTPROPERTY(id, 'IsTable') = 1)
begin
	GOTO createView;
--	drop table akkradm.IO_VERANSTALTUNG;
end;

create table akkradm.IO_VERANSTALTUNG(
	VESG_ID				UDT_ID IDENTITY NOT FOR REPLICATION,

	MAND_ID				UDT_MANDANT		NOT NULL,
	EIGE_ID				UDT_EIGENTUEMER	NOT NULL,
	
	ANBO_ID						UDT_ID 	NOT NULL,		                                 
	VOTE_ID						UDT_ID 	NOT NULL,		
	GUEB_ID						UDT_ID 	NOT NULL,
	VERR_ID						UDT_ID 	NOT NULL,	

	VESG_NR						nvarchar(10)	NOT NULL,
	VESG_NR2				    nvarchar(25)	NOT NULL,
	VESG_KZABRUFVERANSTALTUNG   UDT_BOOLEAN		NOT NULL,
	VESG_KZVORLAEUFIGERTERMIN   UDT_BOOLEAN		NOT NULL,
	VESG_KZFESTERTERMIN			UDT_BOOLEAN		NOT NULL,
	VESG_AUFABRUFBIS			datetime		NOT NULL,
	VESG_BEGINN					datetime		NOT NULL,
	VESG_#BEGINN_ZEIT			UDT_UHRZEIT		NOT NULL,
	VESG_ENDE					datetime		NOT NULL,
	VESG_#ENDE_ZEIT             UDT_UHRZEIT		NOT NULL,
	VESG_THEMA					nvarchar(500)	NOT NULL,

	VESG_TEILNEHMERBEITRAG		UDT_BETRAG		NOT NULL,
	VESG_VERANSTALTUNGORT		nvarchar(255)	NOT NULL,
	VESG_ANMELDESCHLUSS			datetime		NOT NULL,
	VESG_LEITUNG				nvarchar(4000)	NOT NULL,
	VESG_DOZENTEN				nvarchar(4000)	NOT NULL,
	VESG_ZWISCHENTERMINE		nvarchar(255)	NOT NULL,
	VESG_ZUSATZINFORMATIONEN	nvarchar(500)	NOT NULL,
--	IO_VERANSTALTUNG_BEHINDERTENGERECHTE_AUSSTATTUNG	NULL,
	VEST_CODE					nvarchar(25)	NOT NULL,



	
	
	VESG_PTS_VEST       UDT_USER	NOT NULL,
	VESG_USER_VEST	    UDT_PTS		NOT NULL,

	VESG_USER			UDT_USER	NOT NULL,
	VESG_PTS			UDT_PTS		NOT NULL,
	VESG_#PTS			UDT_#PTS	NULL,	
	VESG_ID_INT			UDT_ID_0	NOT NULL,
	VESG_UQID			UDT_UQID	NOT NULL ROWGUIDCOL,
	VESG_KZ_FREIGABE	UDT_BOOLEAN	NOT NULL,
	VESG_KZ_REPLIKATION	UDT_BOOLEAN	NOT NULL,
	VESG_KZ_GELOESCHT	UDT_BOOLEAN	NOT NULL,

	CONSTRAINT PK_VESG PRIMARY KEY CLUSTERED( VESG_ID )
);

CREATE UNIQUE INDEX VESG_IX_01_U ON akkradm.IO_VERANSTALTUNG( VESG_UQID );
CREATE INDEX		VESG_IX_02	 ON akkradm.IO_VERANSTALTUNG( VESG_KZ_GELOESCHT );

createView:

if not exists ( select * from sysobjects where id = object_id('akkradm.T_VERANSTALTUNG') and OBJECTPROPERTY(id, 'IsView') = 1)
begin
	exec( N'create view akkradm.T_VERANSTALTUNG as select * from INFORMATION_SCHEMA.TABLES;' );
end
GO

alter view akkradm.T_VERANSTALTUNG(
		VESG_ID,
		ANBO_ID,
		VOTE_ID,
		GUEB_ID,
		VERR_ID,

		VESG_NR,
		VESG_NR2,
		VESG_KZABRUFVERANSTALTUNG,
		VESG_KZVORLAEUFIGERTERMIN,
		VESG_KZFESTERTERMIN,
		VESG_AUFABRUFBIS,
		VESG_BEGINN,
		VESG_#BEGINN_ZEIT,
		VESG_ENDE,
		VESG_#ENDE_ZEIT,
		VESG_THEMA,
		VESG_TEILNEHMERBEITRAG,
		VESG_VERANSTALTUNGORT,
		VESG_ANMELDESCHLUSS,
		VESG_LEITUNG,
		VESG_DOZENTEN,
		VESG_ZWISCHENTERMINE,
		VESG_ZUSATZINFORMATIONEN,
--		IO_VERANSTALTUNG_BEHINDERTENGERECHTE_AUSSTATTUNG,
		VEST_CODE,

		VESG_PTS_VEST,
		VESG_USER_VEST,

		VESG_USER,
		VESG_PTS,
		VESG_#PTS

) as
select	VESG_ID,
		ANBO_ID,
		VOTE_ID,
		GUEB_ID,
		VERR_ID,

		VESG_NR,
		VESG_NR2,
		VESG_KZABRUFVERANSTALTUNG,
		VESG_KZVORLAEUFIGERTERMIN,
		VESG_KZFESTERTERMIN,
		VESG_AUFABRUFBIS,
		VESG_BEGINN,
		VESG_#BEGINN_ZEIT,
		VESG_ENDE,
		VESG_#ENDE_ZEIT,
		VESG_THEMA,
		VESG_TEILNEHMERBEITRAG,
		VESG_VERANSTALTUNGORT,
		VESG_ANMELDESCHLUSS,
		VESG_LEITUNG,
		VESG_DOZENTEN,
		VESG_ZWISCHENTERMINE,
		VESG_ZUSATZINFORMATIONEN,
--		IO_VERANSTALTUNG_BEHINDERTENGERECHTE_AUSSTATTUNG,
		VEST_CODE,

		VESG_PTS_VEST,
		VESG_USER_VEST,

		VESG_USER,
		VESG_PTS,
		VESG_#PTS

from	akkradm.IO_VERANSTALTUNG
where	VESG_KZ_GELOESCHT = 0;

GO
