/*	
 * topdev GmbH, erstellt am 30.09.2009 10:00
 *
 * $Author: Maribel Zamorano $
 * $Date: 2009-09-30 10:00:56 $
 * $Rev: _ $
 * -------------------------------------------
 * $Workfile: (01) akkradm.Akkreditierungsstelle.sql $
 *
 */

if exists ( select * from sysobjects where id = object_id('akkradm.IO_AKKREDITIERUNGSSTELLE') and OBJECTPROPERTY(id, 'IsTable') = 1)
begin
	GOTO createView;
--	drop table akkradm.IO_AKKREDITIERUNGSSTELLE;
end;

create table akkradm.IO_AKKREDITIERUNGSSTELLE(
	AKRS_AKKREDITIERUNGSSTELLEID	UDT_ID IDENTITY NOT FOR REPLICATION,


	MAND_ID				UDT_MANDANT		NOT NULL,
	EIGE_ID				UDT_EIGENTUEMER	NOT NULL,

	DIEN_ID             UDT_ID	NOT NULL,


	AKRS_NAMEVOLL				nvarchar(202)	NOT NULL,
	AKRS_STRASSE				nvarchar(60)	NOT NULL,
	AKRS_HAUSNUMMER				UDT_ANZAHL_I	NOT NULL,
	AKRS_HAUSNUMMERNZUSATZ		nvarchar(30)	NOT NULL,
	AKRS_POSTLEITZAHL			nvarchar(20)	NOT NULL,
	AKRS_ORT					nvarchar(40)	NOT NULL,
	AKRS_EMAIL					nvarchar(255)	NOT NULL,
	AKRS_TELEFON				nvarchar(255)	NOT NULL,
	AKRS_MOBILTELEFON			nvarchar(255)	NOT NULL,
	AKRS_FAX					nvarchar(255)	NOT NULL,
	AKRS_BRIEFFENSTERANSCHRIFT	nvarchar(255)	NOT NULL,
	AKRS_BRIEFKOPF1				nvarchar(100)	NOT NULL,
	AKRS_BRIEFKOPF2				nvarchar(100)	NOT NULL,
	AKRS_BRIEFKOPF3				nvarchar(100)	NOT NULL,

	AKRS_ZUSTAENDIGKEITSBEREICHID			UDT_ANZAHL_I	NOT NULL,
	AKRS_ZUSTAENDIGKEITSBEREICHBEZEICHNUNG 	nvarchar(200)	NULL,
	AKRS_LOGOID								UDT_ANZAHL_I	NOT NULL,

		

	AKRS_USER			UDT_USER	NOT NULL,
	AKRS_PTS			UDT_PTS		NOT NULL,
	AKRS_#PTS			UDT_#PTS	NULL,	
	AKRS_ID_INT			UDT_ID_0	NOT NULL,
	AKRS_UQID			UDT_UQID	NOT NULL ROWGUIDCOL,
	AKRS_KZ_FREIGABE	UDT_BOOLEAN	NOT NULL,
	AKRS_KZ_REPLIKATION	UDT_BOOLEAN	NOT NULL,
	AKRS_KZ_GELOESCHT	UDT_BOOLEAN	NOT NULL,

	CONSTRAINT PK_AKRS PRIMARY KEY CLUSTERED( AKRS_AKKREDITIERUNGSSTELLEID )
);

CREATE UNIQUE INDEX AKRS_IX_01_U ON akkradm.IO_AKKREDITIERUNGSSTELLE( AKRS_UQID );
CREATE INDEX		AKRS_IX_02	 ON akkradm.IO_AKKREDITIERUNGSSTELLE( AKRS_KZ_GELOESCHT );

createView:

if not exists ( select * from sysobjects where id = object_id('akkradm.T_AKKREDITIERUNGSSTELLE') and OBJECTPROPERTY(id, 'IsView') = 1)
begin
	exec( N'create view akkradm.T_AKKREDITIERUNGSSTELLE as select * from INFORMATION_SCHEMA.TABLES;' );
end
GO

alter view akkradm.T_AKKREDITIERUNGSSTELLE(
		AKRS_AKKREDITIERUNGSSTELLEID,

		DIEN_ID,

		AKRS_NAMEVOLL,
		AKRS_STRASSE,
		AKRS_HAUSNUMMER,
		AKRS_HAUSNUMMERNZUSATZ,
		AKRS_POSTLEITZAHL,
		AKRS_ORT,
		AKRS_EMAIL,
		AKRS_TELEFON,
		AKRS_MOBILTELEFON,
		AKRS_FAX,
		AKRS_BRIEFFENSTERANSCHRIFT,
		AKRS_BRIEFKOPF1,
		AKRS_BRIEFKOPF2,
		AKRS_BRIEFKOPF3,

		AKRS_ZUSTAENDIGKEITSBEREICHID,
		AKRS_ZUSTAENDIGKEITSBEREICHBEZEICHNUNG,
		AKRS_LOGOID,

		AKRS_USER,
		AKRS_PTS,
		AKRS_#PTS

) as
select	AKRS_AKKREDITIERUNGSSTELLEID,

		DIEN_ID,

		AKRS_NAMEVOLL,
		AKRS_STRASSE,
		AKRS_HAUSNUMMER,
		AKRS_HAUSNUMMERNZUSATZ,
		AKRS_POSTLEITZAHL,
		AKRS_ORT,
		AKRS_EMAIL,
		AKRS_TELEFON,
		AKRS_MOBILTELEFON,
		AKRS_FAX,
		AKRS_BRIEFFENSTERANSCHRIFT,
		AKRS_BRIEFKOPF1,
		AKRS_BRIEFKOPF2,
		AKRS_BRIEFKOPF3,

		AKRS_ZUSTAENDIGKEITSBEREICHID,
		AKRS_ZUSTAENDIGKEITSBEREICHBEZEICHNUNG,
		AKRS_LOGOID,


		AKRS_USER,
		AKRS_PTS,
		AKRS_#PTS

from	akkradm.IO_AKKREDITIERUNGSSTELLE
where	AKRS_KZ_GELOESCHT = 0;

GO
