

-- STATEMENTS FOR TESTING STORED PROCEDURES


--insert into akkradm.IO_AKKREDITIERUNGSSTELLE(DIEN_ID,	AKRS_NAMEVOLL,AKRS_STRASSE,AKRS_HAUSNUMMER,AKRS_HAUSNUMMERNZUSATZ,AKRS_POSTLEITZAHL,
--						AKRS_ORT,AKRS_EMAIL,AKRS_TELEFON,AKRS_MOBILTELEFON,AKRS_FAX,
--						AKRS_BRIEFFENSTERANSCHRIFT,AKRS_BRIEFKOPF1,AKRS_BRIEFKOPF2,AKRS_BRIEFKOPF3,
--						AKRS_ZUSTAENDIGKEITSBEREICHID,AKRS_ZUSTAENDIGKEITSBEREICHBEZEICHNUNG,AKRS_LOGOID )
--					    values( 4,N'test',N'test',1,N'test',N'test',N'test',N'test',N'test',N'test',N'test',N'test',N'test',2,N'test',3 );

declare	@AKRS_AKKREDITIERUNGSSTELLEID	UDT_ANZAHL_I, @AKRS_user UDT_USER, @AKRS_xpts UDT_#PTS,
	@AKRS_NAMEVOLL	nvarchar(202),	@AKRS_STRASSE	nvarchar(60),@AKRS_HAUSNUMMER	UDT_ANZAHL_I ,
	@AKRS_HAUSNUMMERNZUSATZ	nvarchar(30),@AKRS_POSTLEITZAHL	nvarchar(20),@AKRS_ORT nvarchar(40),@AKRS_EMAIL	nvarchar(255),
	@AKRS_TELEFON	nvarchar(255),@AKRS_MOBILTELEFON	nvarchar(255),@AKRS_FAX	nvarchar(255),@AKRS_BRIEFFENSTERANSCHRIFT	nvarchar(255),@AKRS_BRIEFKOPF1	nvarchar(100),@AKRS_BRIEFKOPF2	nvarchar(100),
	@AKRS_BRIEFKOPF3	nvarchar(100),@AKRS_ZUSTAENDIGKEITSBEREICHID	UDT_ANZAHL_I,
	@AKRS_ZUSTAENDIGKEITSBEREICHBEZEICHNUNG nvarchar(200),@AKRS_LOGOID	UDT_ANZAHL_I;

set @AKRS_AKKREDITIERUNGSSTELLEID = 0;
set @AKRS_user = null;
set	@AKRS_xpts = null;

set	@AKRS_NAMEVOLL							= N'TEST';
set	@AKRS_STRASSE							= N'TEST';
set	@AKRS_HAUSNUMMER						= 1;
set	@AKRS_HAUSNUMMERNZUSATZ					= N'TEST';
set	@AKRS_POSTLEITZAHL						= N'TEST';
set	@AKRS_ORT								= N'TEST';
set	@AKRS_EMAIL								= N'TEST';
set	@AKRS_TELEFON							= N'TEST';
set	@AKRS_MOBILTELEFON						= N'TEST';
set	@AKRS_FAX								= N'TEST';
set @AKRS_BRIEFFENSTERANSCHRIFT				= N'TEST';
set	@AKRS_BRIEFKOPF1						= N'TEST';
set	@AKRS_BRIEFKOPF2						= N'TEST';
set	@AKRS_BRIEFKOPF3						= N'TEST';
set	@AKRS_ZUSTAENDIGKEITSBEREICHID			= 2;
set	@AKRS_ZUSTAENDIGKEITSBEREICHBEZEICHNUNG = N'TEST';
set	@AKRS_LOGOID							= 7;

begin transaction
begin try

	exec akkradm.pss_AKRS_IUD
		@SESSION_ID	= N'471174114711',
		@USER		= N'ThomasStangner',

		@AKRS_AKKREDITIERUNGSSTELLEID	= @AKRS_AKKREDITIERUNGSSTELLEID output,
		@AKRS_USER	= @AKRS_user,
		@AKRS_XPTS	= @AKRS_xpts,

		@AAKT_CODE	= 10,			-- 10 = insert, 20 = update, 30 = logical delete, 90 = physical delete

	--> business columns
		@DIEN_ID				= 4711,

		@AKRS_NAMEVOLL							= @AKRS_NAMEVOLL,
		@AKRS_STRASSE							= @AKRS_STRASSE,
		@AKRS_HAUSNUMMER						= @AKRS_HAUSNUMMER,
		@AKRS_HAUSNUMMERNZUSATZ					= @AKRS_HAUSNUMMERNZUSATZ,
		@AKRS_POSTLEITZAHL						= @AKRS_POSTLEITZAHL,
		@AKRS_ORT								= @AKRS_ORT,
		@AKRS_EMAIL								= @AKRS_EMAIL,
		@AKRS_TELEFON							= @AKRS_TELEFON,
		@AKRS_MOBILTELEFON						= @AKRS_MOBILTELEFON,
		@AKRS_FAX								= @AKRS_FAX,
		@AKRS_BRIEFFENSTERANSCHRIFT				= @AKRS_BRIEFFENSTERANSCHRIFT,
		@AKRS_BRIEFKOPF1						= @AKRS_BRIEFKOPF1,
		@AKRS_BRIEFKOPF2						= @AKRS_BRIEFKOPF2,
		@AKRS_BRIEFKOPF3						= @AKRS_BRIEFKOPF3,
		@AKRS_ZUSTAENDIGKEITSBEREICHID			= @AKRS_ZUSTAENDIGKEITSBEREICHID,
		@AKRS_ZUSTAENDIGKEITSBEREICHBEZEICHNUNG = @AKRS_ZUSTAENDIGKEITSBEREICHBEZEICHNUNG,
		@AKRS_LOGOID							= @AKRS_LOGOID,
			-->

	--	@KZ_USE_TRANSACTION		= 0,	-- currently not used
		@DEBUG					= 1		-- only for internal usage

	commit transaction;

end try
begin catch
	rollback transaction;

end catch

select	*
from	akkradm.IO_AKKREDITIERUNGSSTELLE
GO