

--insert into akkradm.IO_ANBIETER(GEPA_ID,QUEL_ID,
--						ABIE_NUMMER,ABIE_STEUERNUMMER,ABIE_SCHWERPUNKTE,ABIE_EINRICHTUNG,ABIE_AUSBILDUNG_LEITUNG,
--						ABIE_AUSBILDUNG_PERSONAL,ABIE_ERFAHRUNG_LEITUNG,ABIE_ERFAHRUNG_PERSONAL,
--						ABIE_QUALIFIKATION_LEITUNG,ABIE_QUALIFIKATION_PERSONAL,ABIE_ERWBILDUNG_LEITUNG,
--						ABIE_ERWBILDUNG_PERSONAL,ABIE_WEITERBILDUNG_LEITUNG,ABIE_WEITERBILDUNG_PERSONAL,
--						ABIE_KZ_ZERTIFIZIERT,ZERT_ID,ABIE_ZERTIFIKAT_DATUM,ABIE_ZERTIFIKAT_STELLE,
--						ABIE_QS_LEITBILD,ABIE_QS_NEUE_ENTWICKLUNGEN,ABIE_QS_FESTLEGUNG_LERNZIELE,
--						ABIE_QS_BESTIMMUNG_METHODEN,ABIE_QS_MESSUNG_ZIELERREICHUNG,ABIE_QS_STEUERUNG_OPTIMIERUNG,
--						ABST_ID,ABIE_GRUND_ABST,ABIE_PTS_ABST,ABIE_USER_ABST,
--						ABIE_AKKREDITIERUNG_DATUM,ABIE_KZ_AKKREDITIERT_ANTRAG,ABIE_KZ_AKKREDITIERT_VERORDNUNG)
--					    values( 5,6,1,2,N'Test',N'Test',N'Test',N'Test',N'Test',N'Test',N'Test',N'Test',N'Test',
--						N'Test',N'Test',N'Test',N'Test',N'Test',1,3,'2009-10-05',N'Test',N'Test',N'Test',N'Test',
--						N'Test',N'Test',N'Test',2,N'Test','2009-10-05','mz','2009-10-05',1,1 );



declare	@ABIE_id	UDT_ID, @ABIE_user UDT_USER, @ABIE_xpts UDT_#PTS,
	@GEPA_ID	UDT_ID	,@QUEL_ID	UDT_ID		,@ABIE_NUMMER	nvarchar(25)	,@ABIE_STEUERNUMMER	nvarchar(50)	,
	@ABIE_SCHWERPUNKTE	nvarchar(1000)	,@ABIE_EINRICHTUNG	nvarchar(1000)	,@ABIE_AUSBILDUNG_LEITUNG	nvarchar(1000)	,
	@ABIE_AUSBILDUNG_PERSONAL	nvarchar(1000)	,@ABIE_ERFAHRUNG_LEITUNG	nvarchar(1000)	,
	@ABIE_ERFAHRUNG_PERSONAL nvarchar(1000)	,@ABIE_QUALIFIKATION_LEITUNG	nvarchar(1000)	,@ABIE_QUALIFIKATION_PERSONAL nvarchar(1000)	,
	@ABIE_ERWBILDUNG_LEITUNG	nvarchar(1000)	,@ABIE_ERWBILDUNG_PERSONAL	nvarchar(1000)	,@ABIE_WEITERBILDUNG_LEITUNG	nvarchar(1000)	,
	@ABIE_WEITERBILDUNG_PERSONAL nvarchar(1000)	,@ABIE_KZ_ZERTIFIZIERT	UDT_BOOLEAN	,
	@ZERT_ID UDT_ID	,@ABIE_ZERTIFIKAT_DATUM datetime	,@ABIE_ZERTIFIKAT_STELLE	nvarchar(255),
	@ABIE_QS_LEITBILD	nvarchar(500),@ABIE_QS_NEUE_ENTWICKLUNGEN nvarchar(500),@ABIE_QS_FESTLEGUNG_LERNZIELE	nvarchar(500),@ABIE_QS_BESTIMMUNG_METHODEN	nvarchar(500),
	@ABIE_QS_MESSUNG_ZIELERREICHUNG	nvarchar(500),@ABIE_QS_STEUERUNG_OPTIMIERUNG	nvarchar(500),@ABST_ID UDT_ID	,
	@ABIE_GRUND_ABST	nvarchar(1000),@ABIE_PTS_ABST	UDT_PTS	,
	@ABIE_USER_ABST	UDT_USER,@ABIE_AKKREDITIERUNG_DATUM	datetime,
	@ABIE_KZ_AKKREDITIERT_ANTRAG UDT_BOOLEAN,@ABIE_KZ_AKKREDITIERT_VERORDNUNG UDT_BOOLEAN	;

set @ABIE_id = 0;
set @ABIE_user = null;
set	@ABIE_xpts = null;


set	@ABIE_NUMMER					= N'Test ';
set	@ABIE_STEUERNUMMER				= N'Test ';
set	@ABIE_SCHWERPUNKTE				= N'Test ';
set	@ABIE_EINRICHTUNG				= N'Test ';
set	@ABIE_AUSBILDUNG_LEITUNG		= N'Test ';
set	@ABIE_AUSBILDUNG_PERSONAL		= N'Test ';
set	@ABIE_ERFAHRUNG_LEITUNG			= N'Test ';
set	@ABIE_ERFAHRUNG_PERSONAL		= N'Test ';
set	@ABIE_QUALIFIKATION_LEITUNG		= N'Test ';
set	@ABIE_QUALIFIKATION_PERSONAL	= N'Test ';
set	@ABIE_ERWBILDUNG_LEITUNG		= N'Test ';
set	@ABIE_ERWBILDUNG_PERSONAL		= N'Test ';
set	@ABIE_WEITERBILDUNG_LEITUNG		= N'Test ';
set	@ABIE_WEITERBILDUNG_PERSONAL	= N'Test ';
set	@ABIE_KZ_ZERTIFIZIERT			= 1;

set	@ABIE_ZERTIFIKAT_DATUM			= '2009-10-05';
set	@ABIE_ZERTIFIKAT_STELLE			= N'Test ';
set	@ABIE_QS_LEITBILD				= N'Test ';
set	@ABIE_QS_NEUE_ENTWICKLUNGEN		= N'Test ';
set	@ABIE_QS_FESTLEGUNG_LERNZIELE	= N'Test ';
set	@ABIE_QS_BESTIMMUNG_METHODEN	= N'Test ';
set	@ABIE_QS_MESSUNG_ZIELERREICHUNG = N'Test ';
set	@ABIE_QS_STEUERUNG_OPTIMIERUNG	= N'Test ';

set	@ABIE_GRUND_ABST				= N'Test ';
set	@ABIE_PTS_ABST 					= '2209-10-05';
set	@ABIE_USER_ABST					= N'mz';
set	@ABIE_AKKREDITIERUNG_DATUM		= '2209-10-05';
set	@ABIE_KZ_AKKREDITIERT_ANTRAG	= 1;
set	@ABIE_KZ_AKKREDITIERT_VERORDNUNG = 1;

begin transaction
begin try

	exec akkradm.pss_ABIE_IUD
		@SESSION_ID	= N'471174114711',
		@USER		= N'ThomasStangner',

		@ABIE_ID	= @ABIE_id output,
		@ABIE_USER	= @ABIE_user,
		@ABIE_XPTS	= @ABIE_xpts,

		@AAKT_CODE	= 10,			-- 10 = insert, 20 = update, 30 = logical delete, 90 = physical delete

	--> fachliche Felder

					@GEPA_ID							= 3,
					@QUEL_ID							= 5,
					@ABIE_NUMMER						= @ABIE_NUMMER,
					@ABIE_STEUERNUMMER					= @ABIE_STEUERNUMMER	,
					@ABIE_SCHWERPUNKTE					= @ABIE_SCHWERPUNKTE,
					@ABIE_EINRICHTUNG					= @ABIE_EINRICHTUNG,
					@ABIE_AUSBILDUNG_LEITUNG			= @ABIE_AUSBILDUNG_LEITUNG,
					@ABIE_AUSBILDUNG_PERSONAL			= @ABIE_AUSBILDUNG_PERSONAL,
					@ABIE_ERFAHRUNG_LEITUNG				= @ABIE_ERFAHRUNG_LEITUNG,
					@ABIE_ERFAHRUNG_PERSONAL			= @ABIE_ERFAHRUNG_PERSONAL,
					@ABIE_QUALIFIKATION_LEITUNG			= @ABIE_QUALIFIKATION_LEITUNG,
					@ABIE_QUALIFIKATION_PERSONAL		= @ABIE_QUALIFIKATION_PERSONAL,
					@ABIE_ERWBILDUNG_LEITUNG			= @ABIE_ERWBILDUNG_LEITUNG,
					@ABIE_ERWBILDUNG_PERSONAL			= @ABIE_ERWBILDUNG_PERSONAL,
					@ABIE_WEITERBILDUNG_LEITUNG			= @ABIE_WEITERBILDUNG_LEITUNG,
					@ABIE_WEITERBILDUNG_PERSONAL		= @ABIE_WEITERBILDUNG_PERSONAL,
					@ABIE_KZ_ZERTIFIZIERT				= @ABIE_KZ_ZERTIFIZIERT,
					@ZERT_ID							= 6,
					@ABIE_ZERTIFIKAT_DATUM				= @ABIE_ZERTIFIKAT_DATUM,
					@ABIE_ZERTIFIKAT_STELLE				= @ABIE_ZERTIFIKAT_STELLE,
					@ABIE_QS_LEITBILD					= @ABIE_QS_LEITBILD,
					@ABIE_QS_NEUE_ENTWICKLUNGEN			= @ABIE_QS_NEUE_ENTWICKLUNGEN,
					@ABIE_QS_FESTLEGUNG_LERNZIELE		= @ABIE_QS_FESTLEGUNG_LERNZIELE,
					@ABIE_QS_BESTIMMUNG_METHODEN		= @ABIE_QS_BESTIMMUNG_METHODEN,
					@ABIE_QS_MESSUNG_ZIELERREICHUNG		= @ABIE_QS_MESSUNG_ZIELERREICHUNG,
					@ABIE_QS_STEUERUNG_OPTIMIERUNG		= @ABIE_QS_STEUERUNG_OPTIMIERUNG,
					@ABST_ID							= 2,
					@ABIE_GRUND_ABST					= @ABIE_GRUND_ABST,
					@ABIE_PTS_ABST 						= @ABIE_PTS_ABST,
					@ABIE_USER_ABST						= @ABIE_USER_ABST,
					@ABIE_AKKREDITIERUNG_DATUM			= @ABIE_AKKREDITIERUNG_DATUM,
					@ABIE_KZ_AKKREDITIERT_ANTRAG		= @ABIE_KZ_AKKREDITIERT_ANTRAG,
					@ABIE_KZ_AKKREDITIERT_VERORDNUNG	= @ABIE_KZ_AKKREDITIERT_VERORDNUNG,

	-->
	--	@KZ_USE_TRANSACTION		= 0,	-- wird derzeit nicht verwendet
		@DEBUG					= 1		-- nur für interne Nutzung

	commit transaction;

end try
begin catch
	rollback transaction;

end catch

select	*
from	akkradm.IO_ANBIETER
GO