

--update akkradm.IO_ANGEBOT set ANBO_NUMMER=N'Test2' where ANBO_ID=2;

declare	@ANBO_id	UDT_ID, @ANBO_user UDT_USER, @ANBO_xpts UDT_#PTS,
	@ABIE_ID UDT_ID,@QUEL_ID UDT_ID,
	@ANBO_NUMMER nvarchar(8),@ANBO_NUMMER_ABIE nvarchar(25),@ANBO_AKTENZEICHEN nvarchar(19),
	@ANBO_THEMA nvarchar(500),@ANBO_BESCHREIBUNG nvarchar(max),@ANBO_GESTALTUNG nvarchar(500),@ANBO_ERWERB_FERTIGKEITEN nvarchar(1000),
	@SCHW_ID	 UDT_ID	,@ANBO_DAUER UDT_BETRAG	,@ANBO_LEISTUNGSPUNKTE Integer	,
	@ANBO_URL nvarchar(255)	,@ANBO_TEILNEHMERHINWEIS nvarchar(500),@ANKA_CODE UDT_CODE	,
	@ANBO_KRITERIEN_ERFOLG_TEILNAHME	nvarchar(255),@ANBO_QUALIFIZIERUNG_NACHWEIS	nvarchar(255)	,
	@ANBO_KZ_VERPFLICHTENDE_ERKLAERUNG UDT_BOOLEAN	,@ANST_ID UDT_ID,
	@ANBO_GRUND_ANST nvarchar(1000),@ANBO_PTS_ANST UDT_PTS,@ANBO_USER_ANST UDT_USER;

set @ANBO_id = 1;
set @ANBO_user = 'ThomasStangner';
set	@ANBO_xpts = '2009-10-06 09:22:03.933';


set	@ANBO_NUMMER					=N'Test2';
set	@ANBO_NUMMER_ABIE				=N'Test2';
set	@ANBO_AKTENZEICHEN				=N'Test2';
set	@ANBO_THEMA						=N'Test2';
set	@ANBO_BESCHREIBUNG				=N'Test2';
set	@ANBO_GESTALTUNG				=N'Test2';
set	@ANBO_ERWERB_FERTIGKEITEN		=N'Test2';

set	@ANBO_DAUER						=1;
set	@ANBO_LEISTUNGSPUNKTE			=1;
set	@ANBO_URL						=N'Test';
set	@ANBO_TEILNEHMERHINWEIS			=N'Test';
set	@ANKA_CODE						=N'Test';
set	@ANBO_KRITERIEN_ERFOLG_TEILNAHME	=N'Test';
set	@ANBO_QUALIFIZIERUNG_NACHWEIS	=N'Test';
set	@ANBO_KZ_VERPFLICHTENDE_ERKLAERUNG =1;

set	@ANBO_GRUND_ANST				=N'Test';
set	@ANBO_PTS_ANST					='2009-10-05';
set	@ANBO_USER_ANST					=N'Test';


begin transaction
begin try

	exec akkradm.pss_ANBO_IUD
		@SESSION_ID	= N'471174114711',
		@USER		= N'ThomasStangner',

		@ANBO_ID	= @ANBO_id output,
		@ANBO_USER	= @ANBO_user,
		@ANBO_XPTS	= @ANBO_xpts,

		@AAKT_CODE	= 20,			



		@ABIE_ID						= 3,
		@QUEL_ID						= 4,
		@ANBO_NUMMER					= @ANBO_NUMMER,
		@ANBO_NUMMER_ABIE				= @ANBO_NUMMER_ABIE,
		@ANBO_AKTENZEICHEN				= @ANBO_AKTENZEICHEN,
		@ANBO_THEMA						= @ANBO_THEMA,
		@ANBO_BESCHREIBUNG				= @ANBO_BESCHREIBUNG,
		@ANBO_GESTALTUNG				= @ANBO_GESTALTUNG,
		@ANBO_ERWERB_FERTIGKEITEN		= @ANBO_ERWERB_FERTIGKEITEN,
		@SCHW_ID						= 4,
		@ANBO_DAUER						= @ANBO_DAUER,
		@ANBO_LEISTUNGSPUNKTE			= @ANBO_LEISTUNGSPUNKTE,
		@ANBO_URL						= @ANBO_URL,
		@ANBO_TEILNEHMERHINWEIS			= @ANBO_TEILNEHMERHINWEIS,
		@ANKA_CODE						= @ANKA_CODE,
		@ANBO_KRITERIEN_ERFOLG_TEILNAHME	= @ANBO_KRITERIEN_ERFOLG_TEILNAHME,
		@ANBO_QUALIFIZIERUNG_NACHWEIS	    = @ANBO_QUALIFIZIERUNG_NACHWEIS,
		@ANBO_KZ_VERPFLICHTENDE_ERKLAERUNG  = @ANBO_KZ_VERPFLICHTENDE_ERKLAERUNG,

		@ANST_ID						= 5,
		@ANBO_GRUND_ANST				= @ANBO_GRUND_ANST,
		@ANBO_PTS_ANST					= @ANBO_PTS_ANST,
		@ANBO_USER_ANST					= @ANBO_USER_ANST,

	-->
	--	@KZ_USE_TRANSACTION		= 0,	
		@DEBUG					= 1	

	commit transaction;

end try
begin catch
	rollback transaction;

end catch

select	*
from	akkradm.IO_ANGEBOT
GO